name: Run Python Script
on:
  push:
    paths:
      - 'test_methods.py'
      - 'rpc_methods.json'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.10'

      - name: Install dependencies
        run: pip install requests

      - name: Start local validator and Run Python Script
        run: |
          solana-test-validator & python3 test_methods.py